<script setup lang="ts">
import { IconRefresh, IconSearch, IconShieldCheck } from '@tabler/icons-vue'
import { onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ApiError } from '../api/client'
import { cancelExpedition, deletePlayer, deletePlayerIdentity, getPlayer, getPlayers, grantItem, reconcileExpedition, setPlayerNotifications, type PlayerDetail, type PlayerSummary } from '../api/ecosystem'
import PageHeader from '../components/ui/PageHeader.vue'
import UiDrawer from '../components/ui/UiDrawer.vue'
import UiState from '../components/ui/UiState.vue'
import { useToast } from '../composables/useToast'

const route=useRoute(),router=useRouter(),toast=useToast()
const filters=reactive({query:String(route.query.query??''),platform:String(route.query.platform??''),role:String(route.query.role??''),expedition_status:String(route.query.expedition_status??'')})
const items=ref<PlayerSummary[]>([]),total=ref(0),loading=ref(false),error=ref('')
const selected=ref<PlayerDetail|null>(null),detailOpen=ref(false),detailLoading=ref(false),tab=ref('pet')
const operation=reactive({type:'',item_name:'调查记录',quantity:10,reason:'',confirmation:''}),busy=ref(false)

function params(){const value=new URLSearchParams({page:'1',limit:'50'});Object.entries(filters).forEach(([key,val])=>val&&value.set(key,val));return value}
async function load(){loading.value=true;error.value='';try{const result=await getPlayers(params());items.value=result.items;total.value=result.total}catch(reason){error.value=reason instanceof ApiError?reason.message:'玩家列表加载失败'}finally{loading.value=false}}
async function applyFilters(){await router.replace({query:{...filters}});await load()}
async function clearFilters(){Object.assign(filters,{query:'',platform:'',role:'',expedition_status:''});await applyFilters()}
async function openPlayer(accountId:string){detailOpen.value=true;detailLoading.value=true;selected.value=null;operation.type='';tab.value='pet';try{selected.value=await getPlayer(accountId)}catch(reason){toast.error(reason instanceof Error?reason.message:'玩家详情加载失败')}finally{detailLoading.value=false}}
async function refreshDetail(){if(selected.value)selected.value=await getPlayer(selected.value.account.ID)}
function startOperation(type:string){operation.type=type;operation.reason='';operation.confirmation=''}
async function runOperation(){if(!selected.value||!operation.reason.trim())return toast.error('请填写操作原因');const accountId=selected.value.account.ID;busy.value=true;try{if(operation.type==='grant')await grantItem(accountId,{item_name:operation.item_name,quantity:operation.quantity,reason:operation.reason,idempotency_key:crypto.randomUUID()});if(operation.type==='notifications')await setPlayerNotifications(accountId,!selected.value.notifications.Enabled,operation.reason);if(operation.type.startsWith('identity:'))await deletePlayerIdentity(accountId,Number(operation.type.split(':')[1]),operation.reason);if(operation.type.startsWith('cancel:'))await cancelExpedition(operation.type.split(':')[1],operation.reason);if(operation.type.startsWith('reconcile:'))await reconcileExpedition(operation.type.split(':')[1],operation.reason);if(operation.type==='delete'){await deletePlayer(accountId,operation.confirmation,operation.reason);detailOpen.value=false;await load();return toast.success('玩家数据已删除')}toast.success('操作已完成并写入审计日志');operation.type='';await Promise.all([refreshDetail(),load()])}catch(reason){toast.error(reason instanceof Error?reason.message:'操作失败')}finally{busy.value=false}}
watch(()=>route.query,()=>Object.assign(filters,{query:String(route.query.query??''),platform:String(route.query.platform??''),role:String(route.query.role??''),expedition_status:String(route.query.expedition_status??'')}))
onMounted(load)
</script>

<template><section class="players-page">
  <PageHeader eyebrow="Players" title="玩家管理" description="检索全局账号、宠物、身份、远征与社区关系；敏感身份只展示脱敏值。"><template #actions><button class="btn btn-ghost" @click="load"><IconRefresh :size="17"/>刷新</button></template></PageHeader>
  <form class="filter-bar" @submit.prevent="applyFilters"><label><span>搜索</span><div class="input-icon"><IconSearch :size="16"/><input v-model="filters.query" placeholder="账号 UUID / 宠物名 / 身份尾号"/></div></label><label><span>平台</span><select v-model="filters.platform"><option value="">全部平台</option><option value="onebot">OneBot</option><option value="qq_group">官方群</option><option value="qq_guild">官方频道</option></select></label><label><span>定位</span><select v-model="filters.role"><option value="">全部定位</option><option>探索者</option><option>守护者</option><option>学者</option><option>支援者</option></select></label><label><span>远征</span><select v-model="filters.expedition_status"><option value="">全部状态</option><option value="running">进行中</option><option value="claimed">已结算</option><option value="cancelled">已取消</option></select></label><button class="btn btn-primary" type="submit">筛选</button></form>
  <UiState v-if="error" tone="error" title="玩家列表加载失败" :description="error" action-label="重试" @action="load"/>
  <div v-else class="data-panel"><div class="data-panel-head"><strong>{{total}} 位玩家</strong><span>桌面显示完整表格，手机自动切换摘要卡</span></div><div v-if="loading" class="player-skeleton" aria-label="正在加载玩家"><i v-for="n in 6" :key="n"/></div><UiState v-else-if="items.length===0" title="没有符合条件的玩家" description="新玩家创建存档后会出现在这里；也可以清空筛选重新查询。" action-label="清空筛选" @action="clearFilters"/><div v-else class="desktop-table"><table><thead><tr><th>玩家 / 宠物</th><th>定位</th><th>成长</th><th>身份</th><th>社区</th><th>远征</th><th>操作</th></tr></thead><tbody><tr v-for="row in items" :key="row.account_id"><td><strong>{{row.pet_name||'未领养宠物'}}</strong><small>{{row.account_id}}</small></td><td>{{row.role||'尚未定位'}}</td><td>{{row.growth??0}} · 羁绊 {{row.bond_level??0}}</td><td>{{row.identity_count??0}}</td><td>{{row.community_count??0}}</td><td><span class="status-pill" :data-status="row.expedition_status">{{row.expedition_status||'空闲'}}</span></td><td><button class="btn btn-ghost btn-small" @click="openPlayer(row.account_id)">查看详情</button></td></tr></tbody></table></div><div class="mobile-list"><button v-for="row in items" :key="row.account_id" class="summary-card" @click="openPlayer(row.account_id)"><span><strong>{{row.pet_name||'未领养宠物'}}</strong><small>{{row.account_id.slice(-8)}}</small></span><span>{{row.role||'尚未定位'}} · 成长 {{row.growth??0}}</span><span>{{row.identity_count??0}} 身份 · {{row.community_count??0}} 社区</span></button></div></div>

  <UiDrawer :open="detailOpen" title="玩家全局存档" description="运营修改必须填写原因，并记录到审计日志。" :busy="busy" @close="detailOpen=false">
    <UiState v-if="detailLoading" tone="loading" title="正在读取玩家详情" description="正在组合全局与社区存档。"/>
    <template v-else-if="selected"><div class="detail-id"><IconShieldCheck :size="18"/><code>{{selected.account.ID}}</code></div><nav class="subnav"><button v-for="item in [['pet','宠物'],['inventory','背包'],['codex','图鉴'],['identities','身份'],['expeditions','远征'],['communities','社区']]" :key="item[0]" :class="{active:tab===item[0]}" @click="tab=item[0]">{{item[1]}}</button></nav>
      <div v-if="tab==='pet'&&Object.keys(selected.pet).length" class="pet-summary"><div><small>宠物名称</small><strong>{{selected.pet.Name||'未命名'}}</strong></div><div><small>宠物种类</small><strong>{{selected.pet.PetType||'未设置'}}</strong></div><div><small>定位 / 姿态</small><strong>{{selected.pet.Role||'未定位'}} · {{selected.pet.Stance||'未设置'}}</strong></div><div><small>成长 / 羁绊</small><strong>{{selected.pet.Growth||0}} · Lv.{{selected.pet.BondLevel||1}}</strong></div><div class="wide"><small>技能组</small><strong>{{selected.pet.Skills||'尚未配置技能组'}}</strong></div><div class="wide"><small>性格特质</small><strong>{{selected.pet.Traits||'尚未形成'}}</strong></div></div><UiState v-else-if="tab==='pet'" title="玩家尚未领养宠物" description="领养后会展示定位、姿态、技能、成长和羁绊信息。"/>
      <div v-if="tab==='inventory'&&selected.inventory.length" class="record-list"><div v-for="row in selected.inventory" :key="String(row.ID)"><strong>{{row.ItemName||'未命名物品'}}</strong><span>× {{row.Quantity??0}}</span></div></div><UiState v-else-if="tab==='inventory'" title="背包暂无物品" description="远征奖励或运营补发完成后，物品会出现在这里。"/>
      <div v-if="tab==='codex'&&selected.codex.length" class="record-list"><div v-for="row in selected.codex" :key="String(row.ID)"><strong>{{row.Category||'未分类'}} · {{row.EntryKey||'未命名条目'}}</strong><span>{{row.Progress??0}}%</span></div></div><UiState v-else-if="tab==='codex'" title="暂无图鉴进度" description="完成首次远征后会产生图鉴调查进度。"/>
      <div v-if="tab==='identities'&&selected.identities.length" class="record-list"><div v-for="row in selected.identities" :key="row.id"><span><strong>{{row.platform||'未知平台'}}</strong><small>{{row.scene_type||'未知场景'}} · {{row.subject_id||'已脱敏'}}</small></span><button class="btn btn-danger btn-small" @click="startOperation(`identity:${row.id}`)">解绑</button></div></div><UiState v-else-if="tab==='identities'" title="没有可展示的绑定身份" description="身份信息只展示脱敏结果。"/>
      <div v-if="tab==='expeditions'&&selected.expeditions.length" class="record-list"><div v-for="row in selected.expeditions" :key="String(row.ID)"><span><strong>{{row.Name||'未命名远征'}}</strong><small>{{row.Status||'未知状态'}} · {{row.EndsAt||'-'}}</small></span><span v-if="row.Status==='running'" class="actions"><button class="btn btn-ghost btn-small" @click="startOperation(`cancel:${row.ID}`)">取消</button><button class="btn btn-primary btn-small" @click="startOperation(`reconcile:${row.ID}`)">结算</button></span></div></div><UiState v-else-if="tab==='expeditions'" title="暂无远征记录" description="玩家开始远征后，奖励快照和结算状态会显示在这里。"/>
      <div v-if="tab==='communities'&&selected.communities.length" class="record-list"><div v-for="row in selected.communities" :key="String(row.ID)"><span><strong>{{row.CommunityID||row.community_id||'未知社区'}}</strong><small>贡献 {{row.Contribution??row.contribution??0}} · 救援 {{row.RescueCount??row.rescue_count??0}}</small></span></div></div><UiState v-else-if="tab==='communities'" title="尚未加入社区" description="玩家在群或频道产生社区行为后，关系与贡献会出现在这里。"/>
      <div class="safe-actions"><button class="btn btn-primary" @click="startOperation('grant')">补发固定物品</button><button class="btn btn-ghost" @click="startOperation('notifications')">{{selected.notifications.Enabled?'关闭':'开启'}}主动通知</button><button class="btn btn-danger" @click="startOperation('delete')">删除玩家数据</button></div>
      <form v-if="operation.type" class="operation-box" @submit.prevent="runOperation"><strong>安全操作确认</strong><template v-if="operation.type==='grant'"><label>物品<input v-model="operation.item_name"/></label><label>数量<input v-model.number="operation.quantity" type="number" min="1" max="9999"/></label></template><label>操作原因<textarea v-model="operation.reason" rows="3" placeholder="必填，将写入审计日志"/></label><label v-if="operation.type==='delete'">输入账号末六位确认<input v-model="operation.confirmation"/></label><div class="actions"><button type="button" class="btn btn-ghost" @click="operation.type=''">取消</button><button class="btn btn-danger" :disabled="busy">{{busy?'处理中…':'确认执行'}}</button></div></form>
    </template>
  </UiDrawer>
</section></template>

<style scoped>
.players-page{display:grid;gap:14px}.player-skeleton{display:grid;gap:1px}.player-skeleton i{height:58px;background:linear-gradient(90deg,var(--bg-surface),var(--bg-elevated),var(--bg-surface));background-size:200% 100%;animation:shimmer 1.2s infinite}.detail-id{display:flex;align-items:center;gap:8px;padding:10px 12px;overflow:auto;border-radius:10px;background:var(--bg-elevated)}.subnav{display:flex;gap:6px;margin:16px 0;overflow:auto}.subnav button{padding:8px 10px;border:0;border-radius:8px;background:none;color:var(--text-muted);white-space:nowrap}.subnav button.active{background:var(--accent-soft);color:var(--accent)}.pet-summary{display:grid;grid-template-columns:1fr 1fr;gap:10px}.pet-summary>div{display:grid;padding:12px;border:1px solid var(--border-color);border-radius:10px;background:var(--bg-base)}.pet-summary small,.record-list small{color:var(--text-muted)}.pet-summary .wide{grid-column:1/-1}.record-list{display:grid;gap:8px}.record-list>div{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px;border:1px solid var(--border-color);border-radius:10px}.record-list span:first-child{display:grid}.safe-actions,.actions{display:flex;gap:8px;flex-wrap:wrap}.safe-actions{margin-top:18px;padding-top:18px;border-top:1px solid var(--border-color)}.operation-box{display:grid;gap:12px;margin-top:14px;padding:16px;border-radius:12px;background:var(--bg-elevated)}.operation-box label{display:grid;gap:5px}.operation-box input,.operation-box textarea{padding:9px 11px;border:1px solid var(--border-color);border-radius:9px;background:var(--bg-base);color:var(--text-main)}.operation-box .actions{justify-content:flex-end}.status-pill{padding:4px 8px;border-radius:999px;background:var(--bg-elevated);font-size:12px}.status-pill[data-status=running]{background:var(--warning-soft);color:var(--warning-strong)}@keyframes shimmer{to{background-position:-200% 0}}@media(max-width:600px){.pet-summary{grid-template-columns:1fr}.pet-summary .wide{grid-column:auto}}
</style>
