<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { IconBrandQq, IconCheck, IconCopy, IconPlugConnected, IconSettings } from '@tabler/icons-vue'
import { completeSetup, fetchOnboardingStatus } from '../api/onboarding'
import { getPlatformConfig, getPlatformStatus, savePlatformConfig, type PlatformStatus } from '../api/ecosystem'

type Choice = 'skip' | 'onebot' | 'official' | 'both'
const router = useRouter(), step = ref(0), choice = ref<Choice>('skip'), busy = ref(false), error = ref(''), copied = ref(false), status = ref<PlatformStatus|null>(null)
const form = reactive({ listenAddress:'127.0.0.1', port:8080, onebotToken:'', appId:'', appSecret:'' })
const needsOneBot = computed(()=>choice.value==='onebot'||choice.value==='both')
const needsOfficial = computed(()=>choice.value==='official'||choice.value==='both')
const wsURL = computed(()=>`ws://${form.listenAddress==='0.0.0.0'?'127.0.0.1':form.listenAddress}:${form.port}/v1/ws`)
const choices: {id: Choice; label: string; desc: string; icon: typeof IconSettings}[] = [{id:'onebot',label:'OneBot / NapCat',desc:'使用反向 WebSocket 接入现有 QQ 框架',icon:IconPlugConnected},{id:'official',label:'QQ 官方机器人',desc:'使用 AppID 与 AppSecret 连接官方开放平台',icon:IconBrandQq},{id:'both',label:'两种方式同时使用',desc:'一个后台同时管理两个接入通道',icon:IconCheck},{id:'skip',label:'稍后再配置',desc:'先进入后台熟悉功能，机器人保持离线',icon:IconSettings}]

function newToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));form.onebotToken=btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function copyOneBot(){await navigator.clipboard.writeText(`地址: ${wsURL.value}\nToken: ${form.onebotToken}`);copied.value=true}
async function savePlatform(){error.value='';if(needsOfficial.value&&(!form.appId.trim()||!form.appSecret.trim())){error.value='请同时填写 QQ AppID 和 AppSecret';return}busy.value=true;try{const qq:any={};if(needsOfficial.value){Object.assign(qq,{app_id:form.appId.trim(),app_secret:form.appSecret,group_events_enabled:true,guild_events_enabled:true})}const result=await savePlatformConfig({listen_address:form.listenAddress,port:form.port,onebot:needsOneBot.value?{token:form.onebotToken}:undefined,qq_official:needsOfficial.value?qq:undefined});if(result.port_handoff){error.value='监听地址或端口已更新，请按平台页面提示完成端口切换后继续。';return}status.value=await getPlatformStatus();step.value=2}catch(reason){error.value=reason instanceof Error?reason.message:'平台配置保存失败'}finally{busy.value=false}}
async function finish(){busy.value=true;try{await completeSetup();await router.replace('/')}catch(reason){error.value=reason instanceof Error?reason.message:'首启状态保存失败'}finally{busy.value=false}}
onMounted(async()=>{const onboarding=await fetchOnboardingStatus();if(onboarding.setup_completed){await router.replace('/');return}const config=await getPlatformConfig();form.listenAddress=config.listen_address||'127.0.0.1';form.port=config.port;newToken()})
</script>

<template><main class="setup-page"><section class="setup-shell">
  <header><span class="brand-mark"><IconSettings :size="20"/></span><div><strong>宠物养成</strong><p>首次配置</p></div><span class="progress">{{step+1}} / 3</span></header>
  <section v-if="step===0" class="step"><p class="kicker">欢迎使用 QQ-Pet v0.1.2</p><h1>先选择机器人接入方式</h1><p class="lead">管理员账号已经设置完成。平台接入可以稍后补充，不影响你先进入后台查看。</p><div class="choice-grid">
    <button v-for="item in choices" :key="item.id" :class="{active:choice===item.id}" @click="choice=item.id"><component :is="item.icon" :size="22"/><span><strong>{{item.label}}</strong><small>{{item.desc}}</small></span></button>
  </div><div class="actions"><button class="btn btn-primary" @click="choice==='skip'?step=2:step=1">继续</button></div></section>
  <section v-else-if="step===1" class="step"><p class="kicker">连接机器人</p><h1>填写接入配置</h1><div class="form-grid"><label>监听地址<select v-model="form.listenAddress"><option value="127.0.0.1">仅本机 127.0.0.1</option><option value="0.0.0.0">所有网卡 0.0.0.0</option></select></label><label>后台端口<input v-model.number="form.port" type="number" min="1" max="65535"/></label></div>
    <section v-if="needsOneBot" class="config-block"><h2>OneBot / NapCat</h2><p>在 NapCat 中新建反向 WebSocket，分别填写下面的地址与 Token。</p><label>WebSocket 地址<input :value="wsURL" readonly/></label><label>Token<input v-model="form.onebotToken" type="password"/></label><button class="btn btn-ghost" @click="copyOneBot"><IconCopy :size="16"/>{{copied?'已复制':'复制连接信息'}}</button></section>
    <section v-if="needsOfficial" class="config-block"><h2>QQ 官方机器人</h2><p>密钥只写入当前电脑的安全配置，保存后不会从接口回显。</p><div class="form-grid"><label>AppID<input v-model="form.appId" autocomplete="off"/></label><label>AppSecret<input v-model="form.appSecret" type="password" autocomplete="new-password"/></label></div></section>
    <p v-if="error" class="error" role="alert">{{error}}</p><div class="actions"><button class="btn btn-ghost" @click="step=0">返回</button><button class="btn btn-primary" :disabled="busy" @click="savePlatform">{{busy?'保存中…':'保存并检查'}}</button></div>
  </section>
  <section v-else class="step complete"><span class="complete-icon"><IconCheck :size="30"/></span><p class="kicker">准备完成</p><h1>后台已经可以使用</h1><p class="lead">{{choice==='skip'?'机器人接入已跳过，可随时前往“平台状态”配置。':status?'已保存接入配置，后台会继续显示实时连接状态。':'接入配置已保存。'}}</p><div class="summary"><span><b>官方默认配置</b><small>v0.1.0 SQL 配置方案</small></span><span><b>接入方式</b><small>{{choice==='skip'?'稍后配置':choice==='both'?'OneBot + QQ 官方':choice==='onebot'?'OneBot / NapCat':'QQ 官方机器人'}}</small></span></div><p v-if="error" class="error">{{error}}</p><div class="actions"><button class="btn btn-primary" :disabled="busy" @click="finish">进入运营后台</button></div></section>
  </section></main></template>

<style scoped>.setup-page{min-height:100dvh;display:grid;place-items:center;padding:24px;background:var(--bg-base)}.setup-shell{width:min(840px,100%);overflow:hidden;border:1px solid var(--border-strong);border-radius:var(--radius-dialog);background:var(--bg-surface);box-shadow:var(--shadow-dialog)}header{display:flex;align-items:center;gap:11px;padding:18px 22px;border-bottom:1px solid var(--border-color)}header>div{display:grid}header p{margin:0;color:var(--text-muted);font-size:11px}.brand-mark,.complete-icon{display:grid;place-items:center;width:40px;height:40px;border-radius:12px;background:var(--accent-soft);color:var(--accent)}.progress{margin-left:auto;color:var(--text-muted);font-size:12px}.step{padding:34px}.kicker{margin:0;color:var(--accent);font-size:11px;font-weight:750}.step h1{margin:6px 0 9px;font-size:30px}.lead,.config-block p{color:var(--text-muted)}.choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:24px}.choice-grid button{display:flex;align-items:flex-start;gap:12px;padding:16px;border:1px solid var(--border-color);border-radius:14px;background:var(--bg-base);color:inherit;text-align:left}.choice-grid button.active{border-color:var(--accent);background:var(--accent-soft)}.choice-grid span,.summary span{display:grid}.choice-grid small,.summary small{margin-top:3px;color:var(--text-muted)}.actions{display:flex;justify-content:flex-end;gap:9px;margin-top:24px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form-grid label,.config-block>label{display:grid;gap:6px;color:var(--text-muted)}input,select{min-height:42px;padding:9px 11px;border:1px solid var(--border-color);border-radius:var(--radius-input);background:var(--bg-base);color:var(--text-main)}.config-block{display:grid;gap:12px;margin-top:18px;padding:18px;border:1px solid var(--border-color);border-radius:14px;background:var(--bg-elevated)}.config-block h2,.config-block p{margin:0}.config-block .btn{justify-self:start}.error{padding:10px 12px;border-radius:9px;background:var(--danger-soft);color:var(--danger)}.complete{text-align:center}.complete-icon{width:58px;height:58px;margin:0 auto 16px}.summary{display:grid;grid-template-columns:1fr 1fr;gap:1px;margin-top:22px;overflow:hidden;border:1px solid var(--border-color);border-radius:12px;background:var(--border-color);text-align:left}.summary span{padding:15px;background:var(--bg-base)}@media(max-width:650px){.setup-page{padding:0}.setup-shell{min-height:100dvh;border:0;border-radius:0}.step{padding:26px 18px}.choice-grid,.form-grid,.summary{grid-template-columns:1fr}}</style>
