<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { getAuditLogs } from '../api/ecosystem'
import { useToast } from '../composables/useToast'
const toast=useToast(),items=ref<Record<string,unknown>[]>([]),total=ref(0),loading=ref(false)
const filters=reactive({action:'',target:'',success:''})
async function load(){loading.value=true;try{const params=new URLSearchParams({limit:'50'});Object.entries(filters).forEach(([key,value])=>value&&params.set(key,value));const result=await getAuditLogs(params);items.value=result.items;total.value=result.total}catch(reason){toast.error(reason instanceof Error?reason.message:'审计日志加载失败')}finally{loading.value=false}}
onMounted(load)
</script>
<template><article class="audit-card"><div class="audit-head"><div><h2>运营审计日志</h2><p>所有白名单运营修改均记录操作者、原因、目标、前后值和执行结果。</p></div><button class="btn btn-ghost" @click="load">刷新</button></div><form class="filter-bar" @submit.prevent="load"><label><span>操作类型</span><input v-model="filters.action" placeholder="grant_item"/></label><label><span>目标</span><input v-model="filters.target" placeholder="账号或记录 ID"/></label><label><span>结果</span><select v-model="filters.success"><option value="">全部</option><option value="true">成功</option><option value="false">失败</option></select></label><button class="btn btn-primary">筛选</button></form><div class="data-panel"><div class="data-panel-head"><strong>{{total}} 条记录</strong><span>日志不包含完整 OpenID 或消息正文</span></div><div v-if="loading" class="loading-row">正在加载…</div><div v-else class="desktop-table"><table><thead><tr><th>时间</th><th>操作者</th><th>操作</th><th>目标</th><th>原因</th><th>结果</th></tr></thead><tbody><tr v-for="row in items" :key="String(row.id)"><td>{{row.created_at}}</td><td>{{row.operator}}</td><td><code>{{row.action}}</code></td><td>{{row.target_type}} · {{row.target_id}}</td><td>{{row.reason}}</td><td><span :class="row.success?'success-text':'danger-text'">{{row.success?'成功':'失败'}}</span><small v-if="row.error_message">{{row.error_message}}</small></td></tr></tbody></table></div><div class="mobile-list"><article v-for="row in items" :key="String(row.id)" class="summary-card"><strong>{{row.action}} · {{row.success?'成功':'失败'}}</strong><span>{{row.target_type}} · {{row.target_id}}</span><span>{{row.reason}}</span><small>{{row.created_at}}</small></article></div></div></article></template>
<style scoped>.audit-card{margin-top:16px;padding:20px;background:var(--bg-surface);border:1px solid var(--border-color);border-radius:var(--radius-card)}.audit-head{display:flex;justify-content:space-between;gap:16px}.audit-head h2{margin:0}.audit-head p{margin:4px 0 0;color:var(--text-muted)}.success-text{color:var(--success-strong)}.danger-text{color:var(--danger)}td small{display:block;color:var(--danger)}</style>
