import sqlite3
c = sqlite3.connect("pet_game.db")
print("players", c.execute("select count(*) from player_accounts").fetchone()[0])
print("pets", c.execute("select count(*) from pet_profiles").fetchone()[0])
print("season_token items", c.execute("select count(*) from item_configs where key='season_token'").fetchone()[0])
print("currencies", list(c.execute("select key,name from currency_configs order by sort_order")))
print("legacy", [t[0] for t in c.execute("select name from sqlite_master where type='table' and name in ('adventure_item_configs','player_adventure_inventory_items','player_adventure_wallets','adventure_wallet_ledgers')")])
print("pet_profiles sql has PRIMARY KEY", "PRIMARY KEY" in (c.execute("select sql from sqlite_master where name='pet_profiles'").fetchone()[0] or ""))
print("active_pet_id", "active_pet_id" in (c.execute("select sql from sqlite_master where name='player_accounts'").fetchone()[0] or ""))
print("shop currency", list(c.execute("select currency_key, count(*) from adventure_shop_item_configs group by currency_key")))
print("reward types", list(c.execute("select reward_type, count(*) from reward_track_configs group by reward_type")))
print("items", c.execute("select count(*) from item_configs").fetchone()[0])
print("maps", c.execute("select count(*) from adventure_map_configs").fetchone()[0])
print("species", c.execute("select count(*) from pet_species_configs").fetchone()[0])
