package gameplay

import "errors"

var (
	ErrDatabaseUnavailable   = errors.New("游戏数据库尚未初始化")
	ErrIdentityRequired      = errors.New("玩家身份信息不完整")
	ErrPetRequired           = errors.New("请先领养宠物")
	ErrPetAlreadyExists      = errors.New("已经有同行伙伴")
	ErrInvalidQuantity       = errors.New("数量必须大于零")
	ErrInsufficientItem      = errors.New("物品数量不足")
	ErrInsufficientFunds     = errors.New("余额不足")
	ErrItemNotFound          = errors.New("没有找到这个物品")
	ErrShopItemNotFound      = errors.New("商店里没有这个商品")
	ErrItemUnavailable       = errors.New("这个物品暂时无法获得")
	ErrOutOfStock            = errors.New("商品库存不足")
	ErrOneTimeItem           = errors.New("这个物品每位玩家只能拥有一个")
	ErrNotSellable           = errors.New("这个物品暂时不能出售")
	ErrWrongItemType         = errors.New("这个物品不适合当前操作")
	ErrPetNotHungry          = errors.New("宠物现在还不饿")
	ErrPetTooHungry          = errors.New("宠物太饿了，先喂点东西吧")
	ErrActionCooldown        = errors.New("宠物还想休息一会儿")
	ErrDailyLimit            = errors.New("今天已经陪伴过很多次了")
	ErrPetNameMismatch       = errors.New("宠物名称不匹配")
	ErrPetAlreadyResting     = errors.New("宠物已经在休养")
	ErrPetNotAway            = errors.New("宠物当前不需要找回")
	ErrTreatmentNotNeeded    = errors.New("宠物当前不需要治疗")
	ErrActivityActive        = errors.New("宠物正在进行其他行动")
	ErrTooManyConcurrentRuns = errors.New("同时进行的行动已达上限")
	ErrActivityNotReady      = errors.New("活动还没有完成")
	ErrNoActiveActivity      = errors.New("宠物当前没有进行这项活动")
	ErrAttributeMax          = errors.New("对应属性已经达到上限")
	ErrEvolutionUnavailable  = errors.New("当前没有可进行的形态变化")
	ErrEvolutionRequirements = errors.New("形态变化条件还没有满足")
)
